name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (recursive)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson libarchive-dev libcjson-dev libcap-dev

      - name: Build toolchain
        run: |
          ./buildtoolchain.sh

      - name: Build u-boot
        run: |
          ./builduboot.sh

      - name: Build medtool
        run: |
          ./buildmedtool.sh

      - name: Build linux
        run: |
          ./buildlinux.sh

      - name: Build rootfs
        run: |
          ./buildrootfs.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linuxmd
          path: |
            u-boot/u-boot.bin
            linux/vmlinux
            smolutils/m68k.erofs
